---
- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
