---
- name: Install PHP and dependencies
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Restart Apache to apply PHP
  systemd:
    name: apache2
    state: restarted
